import os

os.environ["DAM_SERVER_ADDRESS"] = "https://XXXXXXXXXXXXXXXXXXX"
os.environ["DAM_ACCOUNT_KEY"] = "1b3XXXXXXXXXXXXXXXXXXXXXXXX"
os.environ["P4PORT"] = 'ssl:XXXXXXXXXXXXXXXX:1666'
os.environ["P4USER"] = 'XXXXXXXXXXXXX'
