import os

os.environ["DAM_SERVER_ADDRESS"] = "https://XXXXXXXXXXXXXXXXXXX"
os.environ["DAM_ACCOUNT_KEY"] = "1b3XXXXXXXXXXXXXXXXXXXXXXXX"
os.environ["AWS_ACCESS_KEY_ID"] = "AKIXXXXXXXXXXXXXXXXXXXXXX"
os.environ["AWS_SECRET_ACCESS_KEY"] = "AKIXXXXXXXXXXXXXXXXXX"
os.environ["AWS_DEFAULT_REGION"] = "us-west-2"
os.environ["P4PORT"] = 'ssl:XXXXXXXXXXXXXXXX:1666'
os.environ["P4USER"] = 'XXXXXXXXXXXXX'
